################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o 


# Each subdirectory must supply rules for building sources it contributes
Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/%.o: ../Libraries/Drivers/CMSIS/DSP/Source/FilteringFunctions/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM C Compiler 5'
	armcc -DSTM32F107xC -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\CMSIS\Device\ST\STM32F1xx" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\CMSIS\Device\ST\STM32F1xx\Include" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\CMSIS\Device\ST\STM32F1xx\Source" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\CMSIS\Device\ST\STM32F1xx\Source\Templates\arm" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\CMSIS\Lib" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\CMSIS\Core\Include" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\STM32F1xx_HAL_Driver\Inc" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\STM32F1xx_HAL_Driver\Inc\Legacy" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Drivers\STM32F1xx_HAL_Driver\Src" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\EWARM" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\EWARM" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Inc" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\Middlewares\Third_Party\FatFs\src" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\CMSIS" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\CMSIS\CoreSupport" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\CMSIS\DeviceSupport" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\CMSIS\DeviceSupport\Startup" -I"C:\Users\Team03\Desktop\STM32_SPI_SDCARD\Old_STM32F1\MDK-ARM" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\LCD" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\STM32_My_API" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\STM32F10x_StdPeriph_Driver_v3.5\inc" -I"C:\Users\Team03\Desktop\2019_Embeded_System_Design_and_Experiment\Term\Source\Libraries\STM32F10x_StdPeriph_Driver_v3.5\src" --c99 -O2 --cpu=cortex-m3 -g -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


